name = 'yulia'
print(name)
name = name.capitalize()
print(name)
name = name.casefold()
print(name)
name = name.center(10, '*')
print(name)
print(name.count('*'))
print(name.encode())
print(name.startswith('**y'))
print(name.startswith('re'))
print(name.endswith('a***'))
print(name.expandtabs(10))
print(name.find('l'))
warrior_name = 'Xena, Princess-Warrior'
age = 3000
s = 'My name is ' + warrior_name + '. I am ' + str(age) + ' years old.'
print(s)
s = 'My name is {}. I am {} years old.'.format(warrior_name, age)
print(s)
s = f'My name is {warrior_name}. I am {age} years old.'
print(s)
print(name.find('g'))
print(name.isalnum())
print(name.isalpha())
print('5'.isdecimal())
print(name.isdigit())
print(name.isidentifier())
print(name.islower())
print(name.isupper())
lst = s.split()
s2 = ''.join(lst)
print(lst)
print(s2)
print(name.ljust(20, 'X'))
print(name.lstrip())
table = name.maketrans('йфяцычувскамепинртгоьшлбщдюзжхэъё', "qazwsxedcrfvtgbyhnujmik,ol.p;[']\\")
print('дуе ы пщ ещ сщвштп'.translate(table))
print(name.partition('lia'))
print(name.replace('yulia', 'yulii'))
print('xlabloxla'.find('x'))
print('xlabloxla'.rfind('x'))
print(name.rsplit('*', 5))
print(name.rstrip('*'))
sent = 'Hello worldds\nblabla ye\nsorry for such strange sentencies'
print(sent)
print(sent.splitlines())
variable = 'HelloMotoYouu'
print(variable)
print(variable.swapcase())
print(sent.title())
print(name.zfill(20))